### ISSUE TITLE
ncm-oned: Remove NCM::Check from oned.pm

### ISSUE THREAD

**Issue by piojo** [quattor/template-library-stratuslab#7]
File opend.pm uses `NCM::Check`, but doesn't use any functions from it.

We are planning to remove this file entirely in 14.12, so please drop this line, or the file will break.

**Comment by jrha** [comment]
@guillaume-philippon?

**Comment by jouvin** [comment]
Should not be considered as a blocker for the 15.4 release... postpone if needed.
